### PR TITLE
Feature fallback textures

### PR DESCRIPTION
**Pull request by basrieter**
I added an option `Show thumbnail as fanart if no fanart is available` to show thumbs as fanart if the fanart is missing. This is a request of some users that don't like the default channel fanart show for missing fanart.

The resolve order for fanart is now:

| Setting = `False` | Setting = `True` |
|----|----|
| Item fanart | Item fanart |
| Parent fanart | Parent remote fanart  |
| Channel fanart | Item remote thumb |
|  | Channel fanart |

So with the setting to `True`: if the item itself does not have fanart set, it will fallback to the parent's fanart, but only if it is a remote (non-channel) fanart. If the parent only has the local, channel fanart, the thumb of the item will be shown.

### CODE REVIEW

**Comment by basrieter** [comment]
This can be tested using https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-fallback-textures.zip. I did not include #1313 and #1314 in this code, so you can check whether this works as expected. 

If so, I will go through all other channels and clean up any code that does the same.

**Comment by basrieter** [comment]
Also removed all of the custom code from the Swedish channels. So please have a look at them.

**Comment by matsarv** [comment]
Is there a new zip-file to download that have the latest changes (Also removed all of the custom code from the Swedish channels) or is the changes in https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-fallback-textures.zip

**Comment by matsarv** [comment]
Add to: resource.language.sv_se\strings.po
msgctxt "#30088"
msgid "Show thumbnail as fanart if no fanart is available"
msgstr "Visa miniatyrbild som fanart om ingen fanart är tillgänglig"

**Comment by basrieter** [comment]
I think all code that set the default thumbs is now gone and I updated the translations (needs a Kodi restart)

**Comment by Snaah** [comment]
This is great! The only thing I wonder is if users will understand what the setting means. "Thumbnail" and "fanart" does not provide information enough. Until (if) another wording is found, I suggest this setting to be on by default as it looks much better.

Well done, both of you!

**Comment by basrieter** [comment]
> This is great! The only thing I wonder is if users will understand what the setting means. "Thumbnail" and "fanart" does not provide information enough. Until (if) another wording is found, I suggest this setting to be on by default as it looks much better.
> 
> Well done, both of you!

Thanks! Personally I don't like the lower resolution fanart that could happen now. So I don't really like to enable it by default. But I am open for suggestions for new translations.

**Comment by basrieter** [comment]
@matsarv can you verify the other channels?

**Pull request merged**
