### PR TITLE
Fix Slam Radio?

### PR DESCRIPTION
**Pull request by finnie2006**
### Functional description
I used a new working url for slam and changed the name from SLAMFM to SLAM!
A working SLAM! Tv url still needs to get found

### Tasks & Activities

- [x] Test SLAM! radio 
- [ ] Find a new working stream url for SLAM! TV

### other question
Why is SLAM! in the submenu 538?
Slam! is not in the talpa group (Formerly 538 Group) anymore
https://en.wikipedia.org/wiki/Talpa_Radio

SLAM!, 2012-2016 (sold to RadioCorp. effective October 3, 2016)

### CODE REVIEW

**Comment by finnie2006** [comment]
#1572

**Comment by basrieter** [comment]
SLAM was there because it used to be in the same streaming back-end. And as Radio 538 has a crappy site, and thus a crappy channel version in Retrospect, I never noticed the SLAM change.

**Comment by finnie2006** [comment]
I was not able to find a stream url for slam tv btw 
@basrieter

**Comment by finnie2006** [comment]
@basrieter Maybe remove slamtv for now because i cant find a working url for it and for slam! itself use the new url i found

**Comment by basrieter** [comment]
Could you update your PR to do this?

**Comment by finnie2006** [comment]
@basrieter

**Comment by finnie2006** [comment]
also maybe for the radio category add more stations like qmusic etc, and add the album art for the radio stations

**Comment by basrieter** [comment]
Is the PNG needed?

**Comment by finnie2006** [comment]
i think every station should show its own logo

**Comment by basrieter** [comment]
I am just going to completely remove Slam for now. All of it.

**Comment by finnie2006** [comment]
Why??

**Comment by finnie2006** [comment]
Just make a new category Radio and put slam there

**Comment by finnie2006** [comment]
I think you should just merge this its better then it was before

**Comment by basrieter** [comment]
Sure, could you update the PR and add a line in the `changelog.txt` at the bottom of `[B]Channel related[/B]` that describes this change.

**Comment by finnie2006** [comment]
Dont merge it yet, it looks like the url changed again and is not working now

**Pull request merged**
