### PR TITLE
New channel: Tweede Kamer Debat Direct.

### PR DESCRIPTION
**Pull request by gvtulder**
### Functional description

This PR adds a new channel for [Tweede Kamer Debat Direct](https://debatdirect.tweedekamer.nl/), the online video service for debates in the Dutch parliament.

### Reasoning

It would be nice to watch live and video-on-demand debates from the Dutch parliament in Kodi.
See also issue #1394.

### Technical description

The PR adds a new `tweedekamer` channel under `channel.videos`. The channel uses the API from https://debatdirect.tweedekamer.nl/ to load the video catalog. This is the same API that is used for the Debat Direct website and apps, but it does not have public documentation.

The channel shows videos in three categories:
* debates from the past few days (as listed on the Debat Direct website and app);
* livestreams for the plenary and committee rooms;
* a search function for the full archive of the website.

The Tweede Kamer API provides `.m3u8` streams with multiple bitrates and subtitles. For some reason these can not be played with InputStream Adaptive, so the channel uses the Retrospect code to extract streams. This function does not currently extract the subtitles from the `.m3u8` file.

### Tasks & Activities

- [ ] Review code to check if this is the correct way to add a new channel
- [ ] Check if `channel.videos` is the correct category for this channel
- [ ] Test livestreams and debate links on a day with active debates

### CODE REVIEW

**Comment by basrieter** [comment]
Thanks for the effort. I will check it soon. However, I currently have some challenges as I broke my shoulder and have a hard time being at a  desk and/or PC at the moment.

One thing I noticed is the icon image that will not come out nicely behind certain backgrounds. Could you try to find a different one with less transparency? The rest of the code looks niced and clean. I will run the unitttests locally and do some code checks later.

**Comment by ErikBrown2** [comment]
> However, I currently have some challenges as I broke my shoulder and have a hard time being at a desk and/or PC at the moment.
>

Sorry to read that, Bas. Hope you will recover soon.

**Comment by basrieter** [comment]
tweedekamer

Is this an option?

**Comment by gvtulder** [comment]
Thanks for the quick response. There's no hurry, so take your time.

The colorful version of the coat of arms might work, but it's not something that's used anywhere on the website.

Before I saw your suggestion I created a version with a dark blue background (same color as the website). Would that be a good solution? There are more channels with a logo on black/white/uniform backgrounds.

**Comment by basrieter** [comment]
That looks much better! I added a small border around it to fit all other icons. If you replace the file, I can merge the PR. 

tweedekamer

NPO broke today (see #1679) so I will need to push out some more updates.

**Comment by gvtulder** [comment]
Done.

**Comment by basrieter** [comment]
Already recreated a PR for the resources: https://github.com/xbmc/repo-resources/pull/367

**Comment by basrieter** [comment]
Last (and final) request: Could you rebase on master and add a line to the changelog.txt under *Channel related*?

**Comment by gvtulder** [comment]
Should be done now.

**Comment by basrieter** [comment]
Seems to be some issue with timestamps: 

```
__________________ TestTweedeKamerChannel.test_search_results __________________

self = <tests.channel_tests.test_chn_tweedekamer.TestTweedeKamerChannel testMethod=test_search_results>

    def test_search_results(self):
        # list of debates on a specific date
>       self._test_folder_url("https://cdn.debatdirect.tweedekamer.nl/search?q=voorbeeld&status[0]=geweest&sortering=relevant&vanaf=0", 5)

tests/channel_tests/test_chn_tweedekamer.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/channel_tests/channeltest.py:55: in _test_folder_url
    items = self.channel.process_folder_list(item)
resources/lib/chn_class.py:303: in process_folder_list
    handler_result = data_parser.Creator(parser_result)
channels/channel.videos/tweedekamer/chn_tweedekamer.py:333: in create_video_items_from_search
    item = self.__create_video_item_for_debate(hit["_source"])
channels/channel.videos/tweedekamer/chn_tweedekamer.py:343: in __create_video_item_for_debate
    date_format="%Y-%m-%dT%H:%M:%S%z")
resources/lib/helpers/datehelper.py:200: in get_date_from_string
    return time.strptime(value, date_format)
/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/_strptime.py:478: in _strptime_time
    return _strptime(data_string, format)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data_string = '2020-01-29T10:15:45+0100', format = '%Y-%m-%dT%H:%M:%S%z'
```
See: https://github.com/retrospect-addon/plugin.video.retrospect/actions/runs/4308108117/jobs/7514069645

Might als be because the Github runners are in UTC time, but I guess the code should be able to handle that? I usually do a check if  a `+`  is present and then do two different format strings.

**Pull request merged**
